// Startup Actions
export const LOAD_ITEM     = 'LOAD_ITEM';
export const LOAD_COMPLETE = 'LOAD_COMPLETE';

// RadonWindow Event Actions
export const NEW_RADON_WINDOW = 'NEW_RADON_WINDOW';
export const DELETE_RADON_WINDOW = 'DELETE_RADON_WINDOW';
export const ACTIVATE_RADON_WINDOW = 'ACTIVATE_RADON_WINDOW';
export const DEACTIVATE_RADON_WINDOW = 'DEACTIVATE_RADON_WINDOW';
export const MINIMIZE_RADON_WINDOW = 'MINIMIZE_RADON_WINDOW';
export const RESTORE_RADON_WINDOW = 'RESTORE_RADON_WINDOW';

// UI Event Actions
    // Editor Window
    export const CREATE_EDITOR_WINDOW = 'CREATE_EDITOR_WINDOW';
    export const DESTROY_EDITOR_WINDOW = 'DESTROY_EDITOR_WINDOW';
    export const BIND_EDITOR_WINDOW = 'BIND_EDITOR_WINDOW';
    export const CLOSE_EDITOR_WINDOW = 'CLOSE_EDITOR_WINDOW';
    export const SET_EDITOR_WINDOW_VISIBLE = 'SET_EDITOR_WINDOW_VISIBLE';

    // Editor Panel
    export const CREATE_EDITOR_PANEL = 'CREATE_EDITOR_PANEL';
    export const DESTROY_EDITOR_PANEL = 'DESTROY_EDITOR_PANEL';
    export const HIDE_EDITOR_PANEL = 'HIDE_EDITOR_PANEL';
    export const SHOW_EDITOR_PANEL = 'SHOW_EDITOR_PANEL';
    export const MINIMIZE_EDITOR_PANEL = 'MINIMIZE_EDITOR_PANEL';
    export const RESTORE_EDITOR_PANEL = 'RESTORE_EDITOR_PANEL';
    export const BEGIN_MOVE_EDITOR_PANEL = 'BEGIN_MOVE_EDITOR_PANEL';
    export const MOVE_EDITOR_PANEL = 'MOVE_EDITOR_PANEL';
    export const TOGGLE_EDITOR_PANEL_VISIBLE = 'TOGGLE_EDITOR_PANEL_VISIBLE';
    export const SET_EDITOR_PANEL_FOCUSED = 'SET_EDITOR_PANEL_FOCUSED';
    export const SET_EDITOR_PANEL_MOVABLE = 'SET_EDTIOR_PANEL_MOVABLE';
    export const TOGGLE_EDITOR_PANEL_MOVABLE = 'TOGGLE_EDITOR_PANEL_MOVABLE';
    export const SET_EDITOR_PANEL_RESIZABLE = 'SET_EDITOR_PANEL_RESIZABLE';
